name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    # Publishing

    - name: dotnet publish
      run: |
        cd src/ApiCatalogWeb
        dotnet publish -c Release -o '../../artifacts/ApiCatalogWeb'
        cd ../..

    # Deploy to Azure

    - name: webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: apisof
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ./artifacts/ApiCatalogWeb
