name: CD

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/cd.yml
      - src/apisof.net/**
      - src/Terrajobst.ApiCatalog/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2

    - name: Get .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.*'

    # Publishing

    - name: dotnet publish
      run: |
        cd src/apisof.net
        dotnet publish -c Release -o '../../artifacts/apisof.net' /p:SourceRevisionId=${{ github.sha }}
        cd ../..

    # Deploy to Azure

    - name: webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: apisof
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ./artifacts/apisof.net
