name: Deploy Site

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/deploy-site.yml
      - src/apisof.net/**
      - src/Terrajobst.ApiCatalog/**

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # We need the full history in order to use Git versioning

    - name: Get .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.*'

    - name: dotnet publish
      run: |
        cd src/apisof.net
        dotnet publish -c Release -o '../../artifacts/site' /p:SourceRevisionId=${{ github.sha }}
        cd ../..

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: artifacts/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Download build
      uses: actions/download-artifact@v3
      with:
        name: site
        path: artifacts/site

    - name: webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: apisof
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ./artifacts/site
