name: Generate Usage NuGet

on:
  workflow_dispatch:
  schedule:
    - cron: '21 09 * * *' # every day at 09:21 AM UTC (01:21 AM PT)

env:
  DOTNET_NOLOGO: true

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # We need the full history in order to use Git versioning

    - name: Get .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.*'

    - name: Generate usage
      env:
        AzureBlobStorageConnectionString: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: |
        cd ./src/GenUsageNuGet
        dotnet run -- crawl
